"""ITGC-formatted raw SM20 event extract (audit workpaper layout).

Companion to sal/itgc_report.py's findings workbook, for a different line
item from the same reference IDR workbooks: "D-3: Audit Log Details,
Extract... for Tcodes SM20 and SM21" asks for the raw log rows themselves,
not SAL's derived findings - an auditor verifying what a specific
extraction actually returned, not what SAL's rules concluded about it.

Kept as its own module rather than growing sal/itgc_report.py: the two
workbooks serialize entirely different source data (raw events vs.
derived findings) into entirely different sheets, sharing only the visual
language (sal/xlsx_style.py) and the general "cover sheet + workpaper"
shape - not enough overlap to justify one shared, larger module per this
repo's "one small, focused module per concern" convention.
"""
import io
from datetime import datetime, timezone

from openpyxl import Workbook
from openpyxl.utils import get_column_letter

from . import xlsx_style
from .export import EVENTS_HEADERS, sanitize_cell_value, sanitize_row


def _format_sap_date(value: str | None) -> str:
    """dat_from/dat_to are SAP DATS strings (YYYYMMDD) - render as
    YYYY-MM-DD for a workpaper reader, matching sal/itgc_report.py's own
    _format_sap_date(). Falls back to the raw value (or empty string) for
    anything else rather than raising, since this only feeds a display.
    """
    if value and len(value) == 8 and value.isdigit():
        return f"{value[0:4]}-{value[4:6]}-{value[6:8]}"
    return value or ""


def _format_filters(filters: dict) -> str:
    parts = []
    for key in ("user", "transaction_code", "report", "instance", "msg_code", "tim_from", "tim_to"):
        value = filters.get(key)
        if not value:
            continue
        parts.append(f"{key}: {', '.join(value) if isinstance(value, list) else value}")
    return "; ".join(parts) if parts else "None (full day, every user/tcode)"


def _build_cover_sheet(wb: Workbook, *, org_name: str, application: str,
                        system_id: str | None, client: str | None, environment: str | None,
                        dat_from: str, dat_to: str, filters: dict, event_count: int,
                        generated_by: str, generated_at: str) -> None:
    ws = wb.active
    ws.title = "Cover Sheet"
    xlsx_style.set_widths(ws, [3, 30, 80])

    row = 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=3)
    title_cell = ws.cell(row=row, column=1,
                          value="SAP Security Audit Log (SM20) — ITGC Extraction Workpaper")
    title_cell.font = xlsx_style.TITLE_FONT
    row += 2

    system_label = system_id or "All configured systems"
    if system_id and environment:
        system_label = f"{system_id} ({environment})"

    kv_rows = [
        ("Client / Organization", org_name),
        ("Application", application),
        ("System", system_label),
        ("Client (SAP mandt)", client or "All"),
        ("Extraction Period", f"{_format_sap_date(dat_from)} to {_format_sap_date(dat_to)}"),
        ("Extraction Parameters", _format_filters(filters)),
        ("Rows Extracted", str(event_count)),
        ("Report Generated By", generated_by),
        ("Report Generated On (UTC)", generated_at),
        ("Data Source", "SAP Security Audit Log (transaction SM20), extracted read-only via RFC "
                         "function module RSAU_API_GET_LOG_DATA"),
        ("Reporting Tool", "Security Audit Log (SAL) Tool"),
    ]
    for label, value in kv_rows:
        ws.cell(row=row, column=2, value=label).font = xlsx_style.LABEL_FONT
        ws.cell(row=row, column=3, value=sanitize_cell_value(value)).alignment = xlsx_style.WRAP
        row += 1
    row += 1

    ws.cell(row=row, column=1, value="Scope & Limitations").font = xlsx_style.SECTION_FONT
    row += 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=3)
    scope_cell = ws.cell(row=row, column=1, value=(
        "This workpaper is a raw extract of SAP Security Audit Log (SM20) events matching "
        "the parameters above, exactly as retained in SAL's own database - it is not a "
        "detection-rule output (see the separate ITGC Findings report for that). Every row "
        "on the Event Log sheet is the literal SM20 record; no analyst judgment or "
        "disposition has been applied to any of them. This tool is read-only and never "
        "writes back to the source SAP system."
    ))
    scope_cell.alignment = xlsx_style.WRAP
    ws.row_dimensions[row].height = 75


def _build_event_log(wb: Workbook, events: list[dict]) -> None:
    ws = wb.create_sheet("Event Log")
    headers = EVENTS_HEADERS
    ws.append(headers)
    xlsx_style.style_header_row(ws, 1, len(headers))
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}1"

    for e in events:
        ws.append(sanitize_row([e.get(h, "") for h in headers]))
    xlsx_style.set_widths(
        ws, [20, 10, 8, 14, 20, 14, 10, 14, 18, 10, 16, 14, 14, 40, 16, 16, 16, 20, 22, 8, 38, 26]
    )
    # No xlsx_style.style_body() here, unlike sal/itgc_report.py's much
    # smaller findings sheets: this is a raw dump of the events table, which
    # can run into the tens/hundreds of thousands of rows for a wide date
    # range. Measured against the live dev DB (~71k rows), per-cell
    # border+wrap styling here cost ~30s on its own (~50s with it vs ~19s
    # without) - by far the largest single cost in generating this workbook.
    # freeze_panes + auto_filter above already make a sheet this size
    # navigable without it.


def build_events_workbook(
    events: list[dict],
    *,
    system_id: str | None,
    client: str | None,
    dat_from: str,
    dat_to: str,
    filters: dict,
    environment: str | None = None,
    org_name: str = "Bristlecone Group",
    application: str = "SAP ECC 6.0",
    generated_by: str = "unknown",
    generated_at: str | None = None,
) -> bytes:
    """Render a raw SM20 event extract into the ITGC workpaper layout:
    Cover Sheet (extraction parameters/methodology) + Event Log (the rows).
    """
    generated_at = generated_at or datetime.now(timezone.utc).isoformat()
    wb = Workbook()
    _build_cover_sheet(
        wb, org_name=org_name, application=application, system_id=system_id,
        client=client, environment=environment, dat_from=dat_from, dat_to=dat_to,
        filters=filters, event_count=len(events),
        generated_by=generated_by, generated_at=generated_at,
    )
    _build_event_log(wb, events)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
